---
matrix:
  include:
    - os: osx
      before_install:
        - brew update
        - brew install gnu-tar
      script: make test
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          packages:
            - devscripts
            - debhelper
      script: debuild -uc -us
